#!/usr/bin/env python

# stdlib
import sys
import os

# App starts here
if __name__ == '__main__':
    if os.path.basename(sys.argv[0]) == 'rscad-control':
        from rtds.commander import commander
        commander()
    else:
        from rtds.streamer2 import streamer
        streamer()

